sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
before_install: gem install bundler -v 1.17.3
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: QpN5aLbzk/2c1JGDqg/e/BUXkWLx9DMkA1bZJ/y60oWCWiw0ahQgS82Hual6+Z0URd7wWkor6bpUjylTlYoORLlWTCCeqhvBBn5Yp2XPcl0/EDVQLjLj29WcBDgCISLc/sMJZ9WmHnw/RuPjiWV5mdSDP5XfVIx2NmPeCprsJFS/i+NbXagR5gjgqzzzzwcJQh4eeTEmknswO/g/mABZY1RhgmoorUkZD91cNWi4zDbMbPV0RI4BpOy2IcgI96/6Bw5s1TQ49Ho8HdAaJ4BZTyTS3a79QPQNfyM2CAOgMUTNfvMnE1gCRazy3OI2fp6KvkTuAD+Vnvuf7RnZooymmL6FQ0p6FJ8laZqvHlW3GFuiBJz2qlZttoZIMinjmjyPzftHMz8GlM1i8/UTpIPN8mhXl8TO9X9HK3V1ZGgM77xYQYqzIqQ3he4XdgrY8qP6BcTsLdp9CrbYGz9XX+zjoy+108ieSteMZ5ec2ck5vDlu8uyslDF47CXhgnR9G0gzS2WAI3JDZiwhtU/izBYh+0xdKa8XvRQzbm0jMNUuuI8h/Mc6LaLgg5kj17IGXmwQs+jxh9CFsdgsZKIDhOPzN30TcAJGx0O90pg4uEBX62nrqlqKwzYc6ujeuz6N3SWR7d3se2FGYAYOPUX0lWj5vq30y6IiCOkhfrFnfXnRYgA=
  gem: cre
  on:
    tags: true
    repo: khalilgharbaoui/cre
